import numpy as np
import matplotlib.pyplot as plt
X = np.linspace(-np.pi, np.pi * 2, 1000)
Y_sin = np.sin(X)
plt.plot(X, Y_sin,c="r",lw=5,ls="-")
#plt.plot(X, Y_sin,'r-'',lw=5)#lw:linewidth
#plt.plot(X, Y_sin,color="r",linewidth=5,linestyle="-")
plt.xlim(X.min()*1.5,X.max()*1.5)
plt.ylim(Y_sin.min()*1.5,Y_sin.max()*1.5)
plt.xticks([-np.pi,-np.pi/2,0,np.pi/2,np.pi],[r'$-\pi$',r'$-\pi/2$',r'$0$',r'$\pi/2$',r'$\pi$'])
plt.yticks([-1,0,1])
ax=plt.gca()
ax.spines['right'].set_color('none') 
ax.spines['top'].set_color('none')
ax.xaxis.set_ticks_position('bottom')
ax.spines['bottom'].set_position(('data',0))
ax.yaxis.set_ticks_position('left')
ax.spines['left'].set_position(('data',0))
plt.show()
plt.savefig("D:/hhh.png")